name = "shortvideo-online-frontend"
compatibility_date = "2023-09-14"
compatibility_flags = ["nodejs_compat"]

[build]
command = "yarn install && yarn build"
cwd = "prototype/frontend"
dist = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"

[env.production]
name = "shortvideo-online-frontend-prod"
route = "shortvideo.online/*"

[env.staging]
name = "shortvideo-online-frontend-staging"
route = "staging.shortvideo.online/*"